coverage:
  if: true
  # acceptable: current >= 40%
codeToTestRatio:
  code:
    - '**/*.go'
    - '!**/*_test.go'
  test:
    - '**/*_test.go'
testExecutionTime:
  acceptable: 2min30sec
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
push:
  if: is_default_branch
comment:
  if: is_pull_request
summary:
  if: true
# body:
#   if: is_pull_request
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
