package central

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/k1LoW/octocov/config"
)

func TestCollectReports(t *testing.T) {
	c := config.New()
	c.Central = &config.ConfigCentral{
		Enable:  true,
		Reports: filepath.Join(testdataDir(t), "reports"),
	}

	ctr := New(c)
	if err := ctr.collectReports(); err != nil {
		t.Fatal(err)
	}

	got := ctr.reports
	if want := 4; len(got) != want {
		t.Errorf("got %v\nwant %v", len(got), want)
	}
}

func TestGenerateBadges(t *testing.T) {
	bd := t.TempDir()
	c := config.New()
	c.Central = &config.ConfigCentral{
		Enable:  true,
		Reports: filepath.Join(testdataDir(t), "reports"),
		Badges:  bd,
	}

	ctr := New(c)
	if err := ctr.collectReports(); err != nil {
		t.Fatal(err)
	}

	if err := ctr.generateBadges(); err != nil {
		t.Fatal(err)
	}

	got := []string{}
	if err := filepath.Walk(bd, func(path string, fi os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if fi.IsDir() {
			return nil
		}
		got = append(got, fi.Name())
		return nil
	}); err != nil {
		t.Fatal(err)
	}

	if want := 4; len(got) != want {
		t.Errorf("got %v\nwant %v", len(got), want)
	}
}

func TestRenderIndex(t *testing.T) {
	c := config.New()
	c.Central = &config.ConfigCentral{
		Enable:  true,
		Reports: filepath.Join(testdataDir(t), "reports"),
	}

	ctr := New(c)
	if err := ctr.collectReports(); err != nil {
		t.Fatal(err)
	}

	buf := &bytes.Buffer{}
	if err := ctr.renderIndex(buf); err != nil {
		t.Fatal(err)
	}

	got := buf.String()
	want := `## Repositories

| Repository | Coverage | Badge |
| --- | --- | --- |
| [k1LoW/awspec](https://github.com/k1LoW/awspec) | 38.8% | ![k1LoW/awspec](./k1LoW/awspec/coverage.svg) |
| [k1LoW/tbls](https://github.com/k1LoW/tbls) | 68.0% | ![k1LoW/tbls](./k1LoW/tbls/coverage.svg) |
| [sebastianbergmann/phpunit](https://github.com/sebastianbergmann/phpunit) | 80.6% | ![sebastianbergmann/phpunit](./sebastianbergmann/phpunit/coverage.svg) |
| [winebarrel/ridgepole](https://github.com/winebarrel/ridgepole) | 95.4% | ![winebarrel/ridgepole](./winebarrel/ridgepole/coverage.svg) |

---

> Generated by [octocov](https://github.com/k1LoW/octocov)
`

	if got != want {
		t.Errorf("got %v\nwant %v", got, want)
	}
}

func testdataDir(t *testing.T) string {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	dir, err := filepath.Abs(filepath.Join(filepath.Dir(wd), "testdata"))
	if err != nil {
		t.Fatal(err)
	}
	return dir
}
